In [ ]:
Преподаватель: Константин Башевой
Домашнее задание

Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3


In [3]:
import numpy as np

In [18]:
# ЗАДАНИЕ 1. РЕШЕНИЕ 1
N = 10
a = np.arange(0, N)

In [20]:
np.flip(a,0)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [27]:
# ЗАДАНИЕ 1. РЕШЕНИЕ 2
N = 10
x = np.arange(0, N)
print(x)
for i in range(N):
    x[i] = N - (i+1)
x

[0 1 2 3 4 5 6 7 8 9]


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [50]:
# ЗАДАНИЕ 2. РЕШЕНИЕ 
N = 10
a = np.diag(np.arange(N), k=0)
b = np.flipud(a).T
a = np.flipud(b)

In [51]:
print(a)
s = sum(a)
print('список сумм построчно =',s)
print('сумма диагональных элементов матрицы =',sum(s))

[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]
список сумм построчно = [9 8 7 6 5 4 3 2 1 0]
сумма диагональных элементов матрицы = 45


In [52]:
# ЗАДАНИЕ 3. РЕШЕНИЕ 

from numpy import linalg

# коэффициенты при переменных в левой части уравнения - a и правая часть - b
a = np.array( [ [4, 2, 1], [1, 3, 0],[0 ,5, 4] ] )
b = np.array( [ 4, 12, -3 ] )
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [53]:
# проверка верности
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True